#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo echo "ENABLED-=1" >> /etc/default/haproxy
sudo echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back
backend http_back
        balance roundrobin
        server 33255-web-01 54.196.45.90 check
        server 33255-web-02 54.90.2.249:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start