#!/usr/bin/env bash
# This script displays list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy
# iT display all processes (a): user-oriented (u), w/wo TTY (x), show heirachy (f)

ps -auxf

