#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080
pkill apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
sudo -u nginx service nginx restart